var players = [
  {
    name: "Daichi Sawamura",
    position: "Captain / Wing Spiker",
    number: 1,
    img: "images/1.jpg",
    desc: "Daichi is the heart and captain of the team. Responsible, calm, and powerful, he ensures stability in both offense and defense. His leadership keeps Karasuno united.",
  },
  {
    name: "Koshi Sugawara",
    position: "Vice Captain / Setter",
    number: 2,
    img: "images/2.jpg",
    desc: "A supportive and kind strategist who boosts team morale and offers tactical plays. Suga’s emotional intelligence is one of Karasuno’s secret weapons.",
  },
  {
    name: "Asahi Azumane",
    position: "Ace",
    number: 3,
    img: "images/3.jpg",
    desc: "Karasuno’s reliable ace, known for his explosive spikes and gentle personality. Despite looking intimidating, he's one of the most sensitive members of the team.",
  },
  {
    name: "Yu Nishinoya",
    position: "Libero",
    number: 4,
    img: "images/4.jpg",
    desc: "The Guardian Deity of Karasuno. A fearless libero with lightning-fast reflexes, fiery personality, and absolute dedication to defense.",
  },
  {
    name: "Ryunosuke Tanaka",
    position: "Wing Spiker",
    number: 5,
    img: "images/5.jpg",
    desc: "Tanaka is loud, confident, and fiercely loyal. His energy boosts the team, and his spikes add consistent offensive pressure.",
  },
  {
    name: "Chikara Ennoshita",
    position: "Wing Spiker",
    number: 6,
    img: "images/6.jpg",
    desc: "Calm, responsible, and often the voice of reason. Ennoshita eventually becomes a respected leader among the members.",
  },
  {
    name: "Hisashi Kinoshita",
    position: "Wing Spiker",
    number: 7,
    img: "images/7.jpg",
    desc: "A hardworking player who slowly gains confidence through practice and determination.",
  },
  {
    name: "Kazuhito Narita",
    position: "Middle Blocker",
    number: 8,
    img: "images/8.jpg",
    desc: "A quiet and supportive member of the team, known for his reliability during crucial moments.",
  },
  {
    name: "Tobio Kageyama",
    position: "Setter",
    number: 9,
    img: "images/9.jpg",
    desc: "A genius setter with pinpoint accuracy and fierce competitiveness. Though initially cold and strict, he learns to trust his teammates and becomes the backbone of Karasuno’s offense.",
  },
  {
    name: "Shoyo Hinata",
    position: "Middle Blocker",
    number: 10,
    img: "images/10.jpg",
    desc: "Hinata is an energetic and passionate player known for his insane jump height, relentless spirit, and unmatched determination. Despite his short stature, he trains harder than anyone to prove that height is not a limitation.",
  },
  {
    name: "Kei Tsukishima",
    position: "Middle Blocker",
    number: 11,
    img: "images/11.jpg",
    desc: "A tall blocker with sharp intellect and strategic thinking. Though initially detached, he grows to love volleyball deeply.",
  },
  {
    name: "Tadashi Yamaguchi",
    position: "Pinch Server",
    number: 12,
    img: "images/12.jpg",
    desc: "Shy but hardworking, Yamaguchi trains tirelessly to master the jump float serve, proving that effort leads to strength.",
  },
];
